package DataAccessLayer.Inventory.DataAccessObjects;

import PresentationLayer.Inventory.DataTransferObjects.DataTransferObject;

import java.sql.*;
import java.util.ArrayList;

public abstract class DataAccessObject {
    Connection c = null;
    String databaseUrl;
    protected String tableName;

    public DataAccessObject() {
        this.databaseUrl = "jdbc:sqlite::resource:module.db";
    }

    public DataAccessObject(String databaseUrl) {
        this.databaseUrl = databaseUrl;
    }

    void close() throws SQLException {
        c.commit();
        c.close();
        c  = null;
    }

    /**
     * If a primary key was autogenerated in the table, returns that key. Otherwise, returns -1
     */
    public int insert(DataTransferObject dataTransferObject) {
        try {
            c = this.connect();
            PreparedStatement stmt = createInsertPreparedStatement(dataTransferObject);
            stmt.executeUpdate();
            ResultSet result = stmt.getGeneratedKeys();

            int generatedId = -1;

            if (result.next()){
                generatedId = result.getInt(1);
            }
            close();
            return generatedId;
        }
        catch (SQLException e) {
            handleError(e);
            try {
                c.close();
                return -1;
            }
            catch (SQLException exception) {
                handleError(e);
                return -1;
            }
        }
    }

    protected abstract PreparedStatement createInsertPreparedStatement(DataTransferObject dataTransferObject) throws SQLException;

    public ArrayList<DataTransferObject> selectAllGeneric (){
        try {
            c = this.connect();
            Statement stmt = c.createStatement();
            String sql = "SELECT * FROM " + tableName;
            ResultSet result = stmt.executeQuery(sql);

            ArrayList<DataTransferObject> dataTransferObjects = new ArrayList<>();
            while (result.next()){
                dataTransferObjects.add(resultToDTO(result));
            }
            close();
            return dataTransferObjects;
        }
        catch (SQLException e) {
            handleError(e);
            return null;
        }
    }

    public <T extends DataTransferObject> T get(int id){
        try {
            c = this.connect();
            Statement stmt = c.createStatement();
            String sql = String.format("SELECT * FROM %s WHERE ID = %d", tableName, id);;
            ResultSet result = stmt.executeQuery(sql);
            T dataTransferObject = null;
            if (result.next()){
                dataTransferObject = resultToDTO(result);
            }
            close();
            return dataTransferObject;
        }
        catch (SQLException e) {
            handleError(e);
            return null;
        }
    }

    public void delete(int id){
        try {
            c = this.connect();
            Statement stmt = c.createStatement();
            String sql = "DELETE FROM " + tableName + " WHERE ID = " + id;
            stmt.executeUpdate(sql);
            close();
        }
        catch (SQLException e) {
            handleError(e);
        }
    }

    void handleError(SQLException e) {
        System.err.println( e.getClass().getName() + ": On table " + tableName + " : " + e.getMessage() );
        try {
            c.close();
        }
        catch (SQLException exception) {
            System.err.println( exception.getClass().getName() + ": On table " + tableName + " : " + exception.getMessage() );
        }
    }

    abstract <T extends DataTransferObject> T resultToDTO(ResultSet resultSet) throws SQLException;


    Connection connect() {
        // SQLite connection string
        String url = "jdbc:sqlite::resource:module.db";
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(databaseUrl);
            conn.setAutoCommit(false);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return conn;
    }
}
